// Static data for Testimonial module
export const TESTIMONIAL_DATA = [];
export const testimonials = [
    {
      id: 1,
      name: 'Bharat Solanki',
      role: 'Director',
      company: 'BiosLab',
      image: '/avatars/1.png',
      logo: '/logos/bioslab.png',
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    },
    {
      id: 2,
      name: 'Sneha Mehta',
      role: 'Founder',
      company: 'AIGen',
      image: '/avatars/2.png',
      logo: '/logos/aigen.png',
      message: 'Superb communication and reliable results every time!',
    },
    {
      id: 3,
      name: 'Ankit Sharma',
      role: 'CTO',
      company: 'NeuroTech',
      image: '/avatars/3.png',
      logo: '/logos/neurotech.png',
      message: 'Working with this team was seamless and productive.',
    },
    {
      id: 4,
      name: 'Neha Patel',
      role: 'COO',
      company: 'MediWare',
      image: '/avatars/4.png',
      logo: '/logos/mediware.png',
      message: 'A brilliant collaboration—truly innovative minds.',
    },
    {
      id: 5,
      name: 'Rajesh Desai',
      role: 'Advisor',
      company: 'TechSpire',
      image: '/avatars/5.png',
      logo: '/logos/techspire.png',
      message: 'A top-tier experience from start to finish!',
    },
    {
      id: 6,
      name: 'Aarti Verma',
      role: 'Product Lead',
      company: 'CodeNest',
      image: '/avatars/6.png',
      logo: '/logos/codenest.png',
      message: 'Always ahead of the curve with visionary tech.',
    },
    {
      id: 7,
      name: 'Bharat Solanki',
      role: 'Director',
      company: 'BiosLab',
      image: '/avatars/1.png',
      logo: '/logos/bioslab.png',
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    },
    {
      id: 8,
      name: 'Sneha Mehta',
      role: 'Founder',
      company: 'AIGen',
      image: '/avatars/2.png',
      logo: '/logos/aigen.png',
      message: 'Superb communication and reliable results every time!',
    },
    {
      id: 9,
      name: 'Ankit Sharma',
      role: 'CTO',
      company: 'NeuroTech',
      image: '/avatars/3.png',
      logo: '/logos/neurotech.png',
      message: 'Working with this team was seamless and productive.',
    },
    {
      id: 10,
      name: 'Neha Patel',
      role: 'COO',
      company: 'MediWare',
      image: '/avatars/4.png',
      logo: '/logos/mediware.png',
      message: 'A brilliant collaboration—truly innovative minds.',
    },
    {
      id: 11,
      name: 'Rajesh Desai',
      role: 'Advisor',
      company: 'TechSpire',
      image: '/avatars/5.png',
      logo: '/logos/techspire.png',
      message: 'A top-tier experience from start to finish!',
    },
    {
      id: 12,
      name: 'Aarti Verma',
      role: 'Product Lead',
      company: 'CodeNest',
      image: '/avatars/6.png',
      logo: '/logos/codenest.png',
      message: 'Always ahead of the curve with visionary tech.',
    },
    {
      id: 13,
      name: 'Bharat Solanki',
      role: 'Director',
      company: 'BiosLab',
      image: '/avatars/1.png',
      logo: '/logos/bioslab.png',
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    },
    {
      id: 14,
      name: 'Sneha Mehta',
      role: 'Founder',
      company: 'AIGen',
      image: '/avatars/2.png',
      logo: '/logos/aigen.png',
      message: 'Superb communication and reliable results every time!',
    },
    // {
    //   id: 15,
    //   name: 'Ankit Sharma',
    //   role: 'CTO',
    //   company: 'NeuroTech',
    //   image: '/avatars/3.png',
    //   logo: '/logos/neurotech.png',
    //   message: 'Working with this team was seamless and productive.',
    // },
    // {
    //   id: 16,
    //   name: 'Neha Patel',
    //   role: 'COO',
    //   company: 'MediWare',
    //   image: '/avatars/4.png',
    //   logo: '/logos/mediware.png',
    //   message: 'A brilliant collaboration—truly innovative minds.',
    // },
    // {
    //   id: 17,
    //   name: 'Rajesh Desai',
    //   role: 'Advisor',
    //   company: 'TechSpire',
    //   image: '/avatars/5.png',
    //   logo: '/logos/techspire.png',
    //   message: 'A top-tier experience from start to finish!',
    // },
    // {
    //   id: 18,
    //   name: 'Aarti Verma',
    //   role: 'Product Lead',
    //   company: 'CodeNest',
    //   image: '/avatars/6.png',
    //   logo: '/logos/codenest.png',
    //   message: 'Always ahead of the curve with visionary tech.',
    // },
    // {
    //   id: 19,
    //   name: 'Bharat Solanki',
    //   role: 'Director',
    //   company: 'BiosLab',
    //   image: '/avatars/1.png',
    //   logo: '/logos/bioslab.png',
    //   message:
    //     'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    // },
    // {
    //   id: 20,
    //   name: 'Sneha Mehta',
    //   role: 'Founder',
    //   company: 'AIGen',
    //   image: '/avatars/2.png',
    //   logo: '/logos/aigen.png',
    //   message: 'Superb communication and reliable results every time!',
    // },
    // {
    //   id: 21,
    //   name: 'Ankit Sharma',
    //   role: 'CTO',
    //   company: 'NeuroTech',
    //   image: '/avatars/3.png',
    //   logo: '/logos/neurotech.png',
    //   message: 'Working with this team was seamless and productive.',
    // },
    // {
    //   id: 22,
    //   name: 'Neha Patel',
    //   role: 'COO',
    //   company: 'MediWare',
    //   image: '/avatars/4.png',
    //   logo: '/logos/mediware.png',
    //   message: 'A brilliant collaboration—truly innovative minds.',
    // },
    // {
    //   id: 23,
    //   name: 'Rajesh Desai',
    //   role: 'Advisor',
    //   company: 'TechSpire',
    //   image: '/avatars/5.png',
    //   logo: '/logos/techspire.png',
    //   message: 'A top-tier experience from start to finish!',
    // },
    // {
    //   id: 24,
    //   name: 'Aarti Verma',
    //   role: 'Product Lead',
    //   company: 'CodeNest',
    //   image: '/avatars/6.png',
    //   logo: '/logos/codenest.png',
    //   message: 'Always ahead of the curve with visionary tech.',
    // },
  ];