// Static data for Stories module
import { icons } from "@/utility/image"
export const BLOG_DATA = [
  {
    slug: "ai-trends-transforming-field-force",
    name: "Phonex Baker",
    role: "Medical Researcher",
    company: "HealthTech Institute",
    image: icons.blogimage1,
    alt: "Doctor preparing AI medicine in lab with test tubes",
    date: "June 15, 2023",
    title: "AI Trends Transforming Field Force to Boost Sales & Maximize ROI",
    excerpt: "How our team developed a breakthrough diagnosis system using machine learning.",
    content: `Ever wonder how AI is shaking up pharma sales? It's all about moving past outdated approaches and embracing smarter ways to connect with healthcare professionals. This article breaks down how artificial intelligence is becoming a powerful assistant for field forces, making every interaction more impactful. Discover the four key trends that are completely transforming the game.`,
    tags: ["AI", "Healthcare", "Research"],
  },
  {
    slug: "reasons-why-pharma-should-move-beyond-generic-crms",
    name: "Samantha Chen",
    role: "Chief Innovation Officer",
    company: "MediSolutions",
    image: icons.blogimage2,
    alt: "Hospital building illustration for patient care article",
    date: "May 22, 2023",
    title: "Reasons Why Pharma Should Move Beyond Generic CRMs to Drive More Prescriptions",
    excerpt: "Exploring how IoT devices are revolutionizing home healthcare management.",
    content: `Is your sales team giving their all, but prescription numbers just aren't budging? It might not be them, but your CRM! Generic systems just don't cut it in the complex world of pharma sales, with all its unique regulations and relationships. This article dives into why your current CRM could be holding you back and what you can do about it to truly boost growth.`,
    tags: ["IoT", "Remote Care", "Technology"],
  },
  {
    slug: "ways-ai-sante-is-streamlining-pharma-stockist-operations",
    name: "Dr. Rajiv Mehta",
    role: "Neurologist",
    company: "Brain Health Center",
    image: icons.blogimage3,
    alt: "Doctor and child discussing neuroscience treatment",
    date: "April 10, 2023",
    title: "Ways AI Sante is Streamlining Pharma Stockist Operations",
    excerpt: "New technologies helping us understand the human brain better than ever before.",
    content: `Juggling pharma stockist operations can feel like a never-ending battle with paperwork and disconnected systems. But what if AI could simplify it all? This article explores how Ai Sante's RxIntel AI is completely transforming how pharmaceutical companies manage their stockists, offering real-time insights and intelligent automation.`,
    tags: ["Neuroscience", "Imaging", "Research"],
  },
  {
    slug: "what-pharma-can-learn-from-tech-industry-ai-adoption",
    name: "Emma Wilson",
    role: "Health Data Scientist",
    company: "DataMed Analytics",
    image: icons.blogimage4,
    alt: "Concerned boy with medicine bottle on table",
    date: "March 5, 2023",
    title: `What Pharma Can Learn from the Tech Industry's Approach to AI Adoption?`,
    excerpt: "How were leveraging analytics to improve treatment plans and save lives.",
    content: `Ever wondered how pharmaceutical companies can speed up AI adoption without risking patient safety? It's a tricky balance, but tech companies offer valuable lessons. This article dives into how pharma can start small with AI in areas like sales and field force management, building confidence and seeing real ROI, before expanding to truly transform the industry.`,
    tags: ["Data Science", "Analytics", "Healthcare"],
  },
]
